database: hsqldb

# Database Settings
spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
    defer-datasource-initialization: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=mysql;
    username: sa
    password:

  # H2 Settings
  h2:
    console:
      enabled: true
      path: /h2-console

  logging:
    level:
      org:
        springframework.web: debug

  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath*:/${database}/data.sql
